### ISSUE TITLE
Problem with choose.dir() on Windows

### ISSUE THREAD

**Issue by KlMichel** [jiaxuanleong/spiro-IJmacros#25]
Hello,
I do not have much experience in R, but with the fantastic SPIRO Assays manual, I have managed to install everything and get it working. I am using Windows 10 with RStudio 2024.04.2 Build 764 and R 4.3.3.
However, I frequently get a problem while trying to run the first R script (cleanup_germination_data.R): The script quits immediately without presenting a dialog to choose a file with the message:

`Fehler in eval(ei, envir) : No germination data found in that directory`

I found that this is a known issue for the `choose.dir()` command:
https://github.com/rstudio/rstudio/issues/13078

As I do not want to downgrade my R installation, I am currently using the workaround to issue a `file.choose()` in the R console before starting the SPIRO Analysis scripts. Probably one could add this to the Troubleshooting tables?! 

Best,
Klaus

**Comment by jonasoh** [comment]
Hi Klaus,
great to hear that you are up and running with SPIRO! 

Thanks for the report -- I wasn't previously aware of this issue. I'll add it to the table!
